import 'package:powersync/powersync.dart';

/// Define the PowerSync schema.
/// All column names use snake_case to match Supabase.
const Schema schema = Schema([
  Table('organizations', [
    Column.text('name'),
    Column.text('domain'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('internal_widgets', [
    Column.text('widget_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('name'),
    Column.text('url'),
    Column.text('date_added'),
    Column.text('image_url'),
    Column.text('alias'),
    Column.text('scope'),
  ]),
  Table('external_widgets', [
    Column.text('widget_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('name'),
    Column.text('alias'),
    Column.text('protocol'),
    Column.text('host'),
    Column.text('url'),
    Column.text('image_url'),
    Column.text('date_added'),
  ]),
  Table('themes', [
    Column.text('theme_id'),
    Column.text('tenant_id'),
    Column.text('name'),
    Column.text('alias'),
    Column.text('json_content'),
    Column.text('author'),
    Column.text('added_date'),
  ]),
  Table('project_notes', [
    Column.text('note_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('title'),
    Column.text('content'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('project_id'),
  ]),
  Table('projects', [
    Column.text('project_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('name'),
    Column.text('description'),
    Column.text('category'),
    Column.text('color'),
    Column.integer('status'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('persons', [
    Column.text('person_id'),
    Column.text('tenant_id'),
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text('date_of_birth'),
    Column.text('gender'),
    Column.text('phone_number'),
    Column.text('profile_image_url'),
    Column.text('cover_image_url'),
    Column.text('avatar_local_path'),
    Column.text('cover_local_path'),
    Column.text('relationship'),
    Column.integer('affection'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('email_addresses', [
    Column.text('email_address_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('email_address'),
    Column.text('email_type'),
    Column.integer('is_primary'),
    Column.text('status'),
    Column.text('verified_at'),
    Column.text('created_at'),
  ]),
  Table('user_accounts', [
    Column.text('account_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('username'),
    Column.text('password_hash'),
    Column.text('primary_email_id'),
    Column.text('role'),
    Column.integer('is_locked'),
    Column.integer('failed_login_attempts'),
    Column.text('last_login_at'),
    Column.text('password_changed_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('profiles', [
    Column.text('profile_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('bio'),
    Column.text('occupation'),
    Column.text('education_level'),
    Column.text('location'),
    Column.text('website_url'),
    Column.text('linkedin_url'),
    Column.text('github_url'),
    Column.text('cover_image_url'),
    Column.text('avatar_local_path'),
    Column.text('cover_local_path'),
    Column.text('timezone'),
    Column.text('preferred_language'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('detail_information', [
    Column.text('cv_address_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('github_url'),
    Column.text('website_url'),
    Column.text('company'),
    Column.text('university'),
    Column.text('location'),
    Column.text('country'),
    Column.text('bio'),
    Column.text('occupation'),
    Column.text('education_level'),
    Column.text('linkedin_url'),
    Column.text('cover_image_url'),
    Column.text('avatar_local_path'),
    Column.text('cover_local_path'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('skills', [
    Column.text('skill_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('skill_name'),
    Column.text('skill_category'),
    Column.text('proficiency_level'),
    Column.integer('years_of_experience'),
    Column.text('description'),
    Column.integer('is_featured'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('financial_accounts', [
    Column.text('account_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('account_name'),
    Column.text('account_type'),
    Column.real('balance'),
    Column.text('currency'),
    Column.integer('is_primary'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('assets', [
    Column.text('asset_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('asset_name'),
    Column.text('asset_category'),
    Column.text('purchase_date'),
    Column.real('purchase_price'),
    Column.real('current_estimated_value'),
    Column.text('currency'),
    Column.text('condition'),
    Column.text('location'),
    Column.text('notes'),
    Column.integer('is_insured'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('transactions', [
    Column.text('transaction_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('category'),
    Column.text('type'),
    Column.real('amount'),
    Column.text('description'),
    Column.text('transaction_date'),
    Column.text('created_at'),
    Column.text('project_id'),
  ]),
  Table('goals', [
    Column.text('goal_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('title'),
    Column.text('description'),
    Column.text('category'),
    Column.integer('priority'),
    Column.text('status'),
    Column.text('target_date'),
    Column.text('completion_date'),
    Column.integer('progress_percentage'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('project_id'),
  ]),
  Table('scores', [
    Column.text('score_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.real('health_global_score'),
    Column.real('social_global_score'),
    Column.real('financial_global_score'),
    Column.real('career_global_score'),
    Column.real('penalty_score'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('habits', [
    Column.text('habit_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('goal_id'),
    Column.text('habit_name'),
    Column.text('description'),
    Column.text('frequency'),
    Column.text('frequency_details'),
    Column.integer('target_count'),
    Column.integer('is_active'),
    Column.text('started_date'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('ai_analysis', [
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('title'),
    Column.text('summary'),
    Column.text('detailed_analysis'),
    Column.text('status'),
    Column.integer('is_featured'),
    Column.text('published_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('category'),
    Column.text('ai_model'),
    Column.text('prompt_context'),
    Column.real('sentiment_score'),
  ]),
  Table('person_widgets', [
    Column.text('person_widget_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('widget_name'),
    Column.text('widget_type'),
    Column.text('configuration'),
    Column.integer('display_order'),
    Column.integer('is_active'),
    Column.text('role'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('health_metrics', [
    Column.text('metric_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('date'),
    Column.integer('steps'),
    Column.integer('heart_rate'),
    Column.real('sleep_hours'),
    Column.integer('water_glasses'),
    Column.integer('exercise_minutes'),
    Column.real('weight_kg'),
    Column.integer('calories_consumed'),
    Column.integer('calories_burned'),
    Column.integer('focus_minutes'),
    Column.real('quest_points'),
    Column.text('updated_at'),
  ]),
  Table('financial_metrics', [
    Column.text('metric_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('date'),
    Column.real('total_balance'),
    Column.real('total_savings'),
    Column.real('total_investments'),
    Column.real('daily_expenses'),
    Column.real('quest_points'),
    Column.text('updated_at'),
  ]),
  Table('project_metrics', [
    Column.text('metric_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('date'),
    Column.integer('tasks_completed'),
    Column.integer('projects_completed'),
    Column.integer('focus_minutes'),
    Column.real('quest_points'),
    Column.text('updated_at'),
  ]),
  Table('social_metrics', [
    Column.text('metric_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('date'),
    Column.integer('contacts_count'),
    Column.integer('total_affection'),
    Column.real('quest_points'),
    Column.text('updated_at'),
  ]),
  Table('meals', [
    Column.text('meal_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('meal_name'),
    Column.text('meal_image_url'),
    Column.real('fat'),
    Column.real('carbs'),
    Column.real('protein'),
    Column.real('calories'),
    Column.text('eaten_at'),
  ]),
  Table('sessions', [
    Column.text('tenant_id'),
    Column.text('local_id'),
    Column.text('jwt'),
    Column.text('username'),
    Column.text('created_at'),
  ]),
  Table('water_logs', [
    Column.text('tenant_id'),
    Column.text('log_id'),
    Column.text('person_id'),
    Column.integer('amount'),
    Column.text('timestamp'),
  ]),
  Table('sleep_logs', [
    // Column.text('id'),
    Column.text('tenant_id'),
    Column.text('log_id'),
    Column.text('person_id'),
    Column.text('start_time'),
    Column.text('end_time'),
    Column.integer('quality'),
  ]),
  Table('exercise_logs', [
    // Column.text('id'),
    Column.text('tenant_id'),
    Column.text('log_id'),
    Column.text('person_id'),
    Column.text('type'),
    Column.integer('duration_minutes'),
    Column.text('intensity'),
    Column.text('timestamp'),
  ]),
  // themes_config is intentionally excluded from PowerSync sync.
  // Theme is a local-only user preference — syncing it would overwrite the
  // user's saved theme with server state on every app restart.
  Table('custom_notifications', [
    // Column.text('id'),
    Column.text('tenant_id'),
    Column.text('notification_id'),
    Column.text('title'),
    Column.text('content'),
    Column.text('scheduled_time'),
    Column.text('repeat_frequency'),
    Column.text('repeat_days'),
    Column.text('category'),
    Column.text('priority'),
    Column.text('person_id'),
    Column.text('icon'),
    Column.integer('is_enabled'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('quotes', [
    // Column.text('id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('content'),
    Column.text('author'),
    Column.integer('is_active'),
    Column.text('created_at'),
  ]),
  Table('quests', [
    // Column.text('id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('title'),
    Column.text('description'),
    Column.text('type'),
    Column.real('target_value'),
    Column.real('current_value'),
    Column.text('category'),
    Column.integer('reward_exp'),
    Column.integer('is_completed'),
    Column.text('created_at'),
    Column.text('image_url'),
    Column.integer('penalty_score'),
  ]),
  Table('days', [
    Column.text('day_id'),
    Column.text('tenant_id'),
    Column.integer('weight'),
    Column.integer('calories_out'),
  ]),
  Table('focus_sessions', [
    Column.text('session_id'),
    Column.text('tenant_id'),
    Column.text('person_id'),
    Column.text('project_id'),
    Column.text('start_time'),
    Column.text('end_time'),
    Column.integer('duration_seconds'),
    Column.text('status'),
    Column.text('task_id'),
    Column.text('notes'),
  ]),
]);
