import 'package:powersync/powersync.dart';

/// Define the PowerSync schema.
/// This must align with the Drift table definitions for synchronized tables.
const Schema schema = Schema([
  Table('internal_widgets', [
    Column.text('name'),
    Column.text('url'),
    Column.text('date_added'),
    Column.text('image_url'),
    Column.text('alias'),
  ]),
  Table('external_widgets', [
    Column.text('name'),
    Column.text('alias'),
    Column.text('protocol'),
    Column.text('host'),
    Column.text('url'),
    Column.text('image_url'),
    Column.text('date_added'),
  ]),
  Table('themes', [
    Column.text('name'),
    Column.text('alias'),
    Column.text('json_content'),
    Column.text('author'),
    Column.text('addedDate'),
  ]),
  Table('project_notes', [
    Column.integer('personID'),
    Column.text('title'),
    Column.text('content'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
    Column.integer('projectID'),
  ]),
  Table('projects', [
    Column.integer('personID'),
    Column.text('name'),
    Column.text('description'),
    Column.text('category'),
    Column.text('color'),
    Column.integer('status'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('persons', [
    Column.text('firstName'),
    Column.text('lastName'),
    Column.text('dateOfBirth'),
    Column.text('gender'),
    Column.text('phoneNumber'),
    Column.text('profileImageUrl'),
    Column.text('relationship'),
    Column.integer('affection'),
    Column.integer('isActive'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('email_addresses', [
    Column.integer('personID'),
    Column.text('emailAddress'),
    Column.text('emailType'),
    Column.integer('isPrimary'),
    Column.text('status'),
    Column.text('verifiedAt'),
    Column.text('createdAt'),
  ]),
  Table('user_accounts', [
    Column.integer('personID'),
    Column.text('username'),
    Column.text('passwordHash'),
    Column.integer('primaryEmailID'),
    Column.text('role'),
    Column.integer('isLocked'),
    Column.integer('failedLoginAttempts'),
    Column.text('lastLoginAt'),
    Column.text('passwordChangedAt'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('profiles', [
    Column.integer('personID'),
    Column.text('bio'),
    Column.text('occupation'),
    Column.text('educationLevel'),
    Column.text('location'),
    Column.text('websiteUrl'),
    Column.text('linkedinUrl'),
    Column.text('githubUrl'),
    Column.text('timezone'),
    Column.text('preferredLanguage'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('cv_addresses', [
    Column.integer('personID'),
    Column.text('githubUrl'),
    Column.text('websiteUrl'),
    Column.text('company'),
    Column.text('university'),
    Column.text('location'),
    Column.text('country'),
    Column.text('bio'),
    Column.text('occupation'),
    Column.text('educationLevel'),
    Column.text('linkedinUrl'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('skills', [
    Column.integer('personID'),
    Column.text('skillName'),
    Column.text('skillCategory'),
    Column.text('proficiencyLevel'),
    Column.integer('yearsOfExperience'),
    Column.text('description'),
    Column.integer('isFeatured'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('financial_accounts', [
    Column.integer('personID'),
    Column.text('accountName'),
    Column.text('accountType'),
    Column.real('balance'),
    Column.text('currency'),
    Column.integer('isPrimary'),
    Column.integer('isActive'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('assets', [
    Column.integer('personID'),
    Column.text('assetName'),
    Column.text('assetCategory'),
    Column.text('purchaseDate'),
    Column.real('purchasePrice'),
    Column.real('currentEstimatedValue'),
    Column.text('currency'),
    Column.text('condition'),
    Column.text('location'),
    Column.text('notes'),
    Column.integer('isInsured'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('transactions', [
    Column.integer('personID'),
    Column.text('category'),
    Column.text('type'),
    Column.real('amount'),
    Column.text('description'),
    Column.text('transactionDate'),
    Column.text('createdAt'),
    Column.integer('projectID'),
  ]),
  Table('goals', [
    Column.integer('personID'),
    Column.text('title'),
    Column.text('description'),
    Column.text('category'),
    Column.integer('priority'),
    Column.text('status'),
    Column.text('targetDate'),
    Column.text('completionDate'),
    Column.integer('progressPercentage'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
    Column.integer('projectID'),
  ]),
  Table('scores', [
    Column.integer('personID'),
    Column.real('healthGlobalScore'),
    Column.real('socialGlobalScore'),
    Column.real('financialGlobalScore'),
    Column.real('careerGlobalScore'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('habits', [
    Column.integer('personID'),
    Column.integer('goalID'),
    Column.text('habitName'),
    Column.text('description'),
    Column.text('frequency'),
    Column.text('frequencyDetails'),
    Column.integer('targetCount'),
    Column.integer('isActive'),
    Column.text('startedDate'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('blog_posts', [
    Column.integer('authorID'),
    Column.text('title'),
    Column.text('slug'),
    Column.text('excerpt'),
    Column.text('content'),
    Column.text('featuredImageUrl'),
    Column.text('status'),
    Column.integer('isFeatured'),
    Column.integer('viewCount'),
    Column.integer('likeCount'),
    Column.text('publishedAt'),
    Column.text('scheduledFor'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('person_widgets', [
    Column.integer('personID'),
    Column.text('widgetName'),
    Column.text('widgetType'),
    Column.text('configuration'),
    Column.integer('displayOrder'),
    Column.integer('isActive'),
    Column.text('role'),
    Column.text('createdAt'),
    Column.text('updatedAt'),
  ]),
  Table('health_metrics', [
    Column.integer('personID'),
    Column.text('date'),
    Column.integer('steps'),
    Column.integer('heartRate'),
    Column.real('sleepHours'),
    Column.integer('waterGlasses'),
    Column.integer('exerciseMinutes'),
    Column.real('weightKg'),
    Column.integer('caloriesConsumed'),
    Column.integer('caloriesBurned'),
    Column.text('updatedAt'),
  ]),
  Table('meals', [
    Column.text('mealName'),
    Column.text('mealImageUrl'),
    Column.real('fat'),
    Column.real('carbs'),
    Column.real('protein'),
    Column.real('calories'),
    Column.text('eatenAt'),
  ]),
  Table('sessions', [
    Column.text('jwt'),
    Column.text('username'),
    Column.text('createdAt'),
  ]),
  Table('water_logs', [
    Column.integer('personID'),
    Column.integer('amount'),
    Column.text('timestamp'),
  ]),
  Table('sleep_logs', [
    Column.integer('personID'),
    Column.text('startTime'),
    Column.text('endTime'),
    Column.integer('quality'),
  ]),
  Table('exercise_logs', [
    Column.integer('personID'),
    Column.text('type'),
    Column.integer('durationMinutes'),
    Column.text('intensity'),
    Column.text('timestamp'),
  ]),
  Table('themes_config', [Column.text('themeName'), Column.text('themePath')]),
  Table('custom_notifications', [
    Column.text('title'),
    Column.text('content'),
    Column.text('scheduledTime'),
    Column.text('repeatFrequency'),
    Column.text('repeatDays'),
    Column.integer('isEnabled'),
    Column.text('createdAt'),
  ]),
  Table('quotes', [
    Column.text('content'),
    Column.text('author'),
    Column.integer('isActive'),
    Column.text('createdAt'),
  ]),
]);
